Refugee manegment/Refugee manegment/Controllers/AddressesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Refugee_manegment.Models;

namespace Refugee_manegment.Controllers
{
    public class AddressesController : Controller
    {
        private readonly WebDbContext _context;

        public AddressesController(WebDbContext context)
        {
            _context = context;
        }

        // GET: Addresses
        public async Task<IActionResult> Index()
        {
            var webDbContext = _context.Address.Include(a => a.Refugee);
            return View(await webDbContext.ToListAsync());
        }

        // GET: Addresses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var address = await _context.Address
                .Include(a => a.Refugee)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (address == null)
            {
                return NotFound();
            }

            return View(address);
        }

        // GET: Addresses/Create
        public IActionResult Create()
        {
            ViewData["RefugeeId"] = new SelectList(_context.refugee, "Id", "Id");
            return View();
        }

        // POST: Addresses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,RefugeeId,Street,City,Country")] Address address)
        {
            if (ModelState.IsValid)
            {
                _context.Add(address);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RefugeeId"] = new SelectList(_context.refugee, "Id", "Id", address.RefugeeId);
            return View(address);
        }

        // GET: Addresses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var address = await _context.Address.FindAsync(id);
            if (address == null)
            {
                return NotFound();
            }
            ViewData["RefugeeId"] = new SelectList(_context.refugee, "Id", "Id", address.RefugeeId);
            return View(address);
        }

        // POST: Addresses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,RefugeeId,Street,City,Country")] Address address)
        {
            if (id != address.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(address);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AddressExists(address.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RefugeeId"] = new SelectList(_context.refugee, "Id", "Id", address.RefugeeId);
            return View(address);
        }

        // GET: Addresses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var address = await _context.Address
                .Include(a => a.Refugee)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (address == null)
            {
                return NotFound();
            }

            return View(address);
        }

        // POST: Addresses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var address = await _context.Address.FindAsync(id);
            if (address != null)
            {
                _context.Address.Remove(address);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AddressExists(int id)
        {
            return _context.Address.Any(e => e.Id == id);
        }
    }
}

Refugee manegment/Refugee manegment/Controllers/EmployementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Refugee_manegment.Models;

namespace Refugee_manegment.Controllers
{
    public class EmployementsController : Controller
    {
        private readonly WebDbContext _context;

        public EmployementsController(WebDbContext context)
        {
            _context = context;
        }

        // GET: Employements
        public async Task<IActionResult> Index()
        {
            var webDbContext = _context.Employements.Include(e => e.Refugee);
            return View(await webDbContext.ToListAsync());
        }

        // GET: Employements/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employement = await _context.Employements
                .Include(e => e.Refugee)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employement == null)
            {
                return NotFound();
            }

            return View(employement);
        }

        // GET: Employements/Create
        public IActionResult Create()
        {
            ViewData["RefugeeId"] = new SelectList(_context.refugee, "Id", "Id");
            return View();
        }

        // POST: Employements/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,RefugeeId,JobTitle,CompanyName,StartDate,EndDate")] Employement employement)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employement);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RefugeeId"] = new SelectList(_context.refugee, "Id", "Id", employement.RefugeeId);
            return View(employement);
        }

        // GET: Employements/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employement = await _context.Employements.FindAsync(id);
            if (employement == null)
            {
                return NotFound();
            }
            ViewData["RefugeeId"] = new SelectList(_context.refugee, "Id", "Id", employement.RefugeeId);
            return View(employement);
        }

        // POST: Employements/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,RefugeeId,JobTitle,CompanyName,StartDate,EndDate")] Employement employement)
        {
            if (id != employement.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employement);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployementExists(employement.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RefugeeId"] = new SelectList(_context.refugee, "Id", "Id", employement.RefugeeId);
            return View(employement);
        }

        // GET: Employements/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employement = await _context.Employements
                .Include(e => e.Refugee)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employement == null)
            {
                return NotFound();
            }

            return View(employement);
        }

        // POST: Employements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employement = await _context.Employements.FindAsync(id);
            if (employement != null)
            {
                _context.Employements.Remove(employement);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployementExists(int id)
        {
            return _context.Employements.Any(e => e.Id == id);
        }
    }
}

Refugee manegment/Refugee manegment/Controllers/RefugeesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Refugee_manegment.Models;

namespace Refugee_manegment.Controllers
{
    public class RefugeesController : Controller
    {
        private readonly WebDbContext _context;

        public RefugeesController(WebDbContext context)
        {
            _context = context;
        }

        // GET: Refugees
        public async Task<IActionResult> Index()
        {
            var refugees = await _context.refugee.ToListAsync();
            return View(refugees);
        }

        // GET: Refugees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (!id.HasValue)
            {
                return BadRequest("Invalid refugee ID.");
            }

            var refugee = await GetRefugeeById(id.Value);
            if (refugee == null)
            {
                return NotFound("Refugee not found.");
            }

            return View(refugee);
        }

        // GET: Refugees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Refugees/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Nationality,DateOfBirth,Status")] Refugee refugee)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(refugee);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, $"Error: {ex.Message}");
                }
            }

            return View(refugee);
        }

        // GET: Refugees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!id.HasValue)
            {
                return BadRequest("Invalid refugee ID.");
            }

            var refugee = await GetRefugeeById(id.Value);
            if (refugee == null)
            {
                return NotFound("Refugee not found.");
            }

            return View(refugee);
        }

        // POST: Refugees/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Nationality,DateOfBirth,Status")] Refugee refugee)
        {
            if (id != refugee.Id)
            {
                return BadRequest("Refugee ID mismatch.");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(refugee);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await RefugeeExists(refugee.Id))
                    {
                        return NotFound("Refugee not found.");
                    }

                    throw;
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, $"Error: {ex.Message}");
                }
            }

            return View(refugee);
        }

        // GET: Refugees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (!id.HasValue)
            {
                return BadRequest("Invalid refugee ID.");
            }

            var refugee = await GetRefugeeById(id.Value);
            if (refugee == null)
            {
                return NotFound("Refugee not found.");
            }

            return View(refugee);
        }

        // POST: Refugees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var refugee = await GetRefugeeById(id);
                if (refugee == null)
                {
                    return NotFound("Refugee not found.");
                }

                _context.refugee.Remove(refugee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"Error: {ex.Message}");
                return RedirectToAction(nameof(Index));
            }
        }

        // Helper function to get refugee by ID
        private async Task<Refugee> GetRefugeeById(int id)
        {
            return await _context.refugee.FirstOrDefaultAsync(r => r.Id == id);
        }

        // Check if refugee exists
        private async Task<bool> RefugeeExists(int id)
        {
            return await _context.refugee.AnyAsync(e => e.Id == id);
        }
    }
}

Refugee manegment/Refugee manegment/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Refugee Management</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS and Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">

    <!-- Custom Styles -->
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background-color: #eef2f3;
        }

        .navbar {
            background-color: #007bff;
        }

        .navbar-brand {
            color: #fff !important;
            font-size: 1.8rem;
            font-weight: bold;
        }

        .navbar-nav .nav-link {
            color: #f8f9fa !important;
        }

        .sidebar {
            position: fixed;
            top: 0;
            left: 0;
            height: 100%;
            width: 250px;
            background-color: #343a40;
            color: white;
            padding-top: 20px;
        }

            .sidebar .nav-link {
                color: #dcdcdc;
            }

                .sidebar .nav-link:hover {
                    color: #fff;
                    background-color: #495057;
                }

        .content-area {
            margin-left: 270px;
            padding: 20px;
        }

        .footer {
            background-color: #007bff;
            color: #fff;
            padding: 10px 0;
        }
    </style>
</head>
<body>
    <!-- Sidebar -->
    <div class="sidebar">
        <ul class="nav flex-column">
            
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Addresses" asp-action="Index"><i class="bi bi-house-door-fill"></i> Addresses</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Employements" asp-action="Index"><i class="bi bi-briefcase-fill"></i> Employments</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="HealthRecords" asp-action="Index"><i class="bi bi-heart-pulse-fill"></i> Health Records</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Sponsorships" asp-action="Index"><i class="bi bi-hand-thumbs-up-fill"></i> Sponsorships</a>
            </li>
        </ul>
    </div>

    <!-- Main content area -->
    <div class="content-area">
        <header>
            <nav class="navbar navbar-expand-sm navbar-light">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Refugees" asp-action="Index">Refugee Management</a>
                    <a class="navbar-brand" asp-area="" asp-controller="Addresses" asp-action="Index">Addresses</a>
                    <a class="navbar-brand" asp-area="" asp-controller="Employments" asp-action="Index">Employments</a>
                    <a class="navbar-brand" asp-area="" asp-controller="HealthRecords" asp-action="Index">Health Records</a>
                    <a class="navbar-brand" asp-area="" asp-controller="Refugees" asp-action="Index">Sponsorships</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                           
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <!-- Main content -->
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <!-- Footer -->
        <footer class="footer">
            <div class="container">
                &copy; 2025 - Refugee Management - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Refugee manegment/Refugee manegment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Refugee Management</title>

    <!-- Add a Google Font (Roboto for modern look) -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <!-- Custom Styles -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Refugee_manegment.styles.css" asp-append-version="true" />

    <!-- Add some custom styling to enhance the UI -->
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background-color: #f4f7f6;
        }

        header {
            background-color: #343a40;
            padding: 10px 0;
        }

        .navbar-brand {
            color: #fff !important;
            font-size: 1.5rem;
            font-weight: bold;
        }

        .navbar-nav .nav-link {
            color: #ddd !important;
            transition: all 0.3s ease;
        }

            .navbar-nav .nav-link:hover {
                color: #fff !important;
                background-color: #495057;
            }

        .container {
            margin-top: 30px;
        }

        .footer {
            background-color: #343a40;
            color: #ddd;
            padding: 10px 0;
        }

            .footer a {
                color: #fff;
            }

                .footer a:hover {
                    color: #f8f9fa;
                    text-decoration: underline;
                }

        /* Sidebar for Admin Layout */
        .sidebar {
            position: fixed;
            top: 0;
            left: 0;
            height: 100%;
            width: 250px;
            background-color: #343a40;
            color: white;
            padding-top: 20px;
            box-shadow: 2px 0 5px rgba(0, 0, 0, 0.1);
        }

            .sidebar .nav-link {
                color: #ddd;
            }

                .sidebar .nav-link:hover {
                    background-color: #495057;
                }

        .content-area {
            margin-left: 270px;
            padding: 20px;
        }
    </style>
</head>
<body>

    <!-- Sidebar -->
    <div class="sidebar">
        <ul class="nav flex-column">
           
            <li class="nav-item">
                <a class="nav-link" href="#">Manage Refugees</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Reports</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Settings</a>
            </li>
        </ul>
        partional name="_loginpartional"/>
    </div>

    <!-- Main content area -->
    <div class="content-area">
        <header>
            <nav class="navbar navbar-expand-sm navbar-light">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Refugee Management</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <!-- Main content -->
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <!-- Footer -->
        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2025 - Refugee Management - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    </div>

    <!-- Bootstrap and custom JS -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>